#!/bin/bash
# 2023-01-31
#
# Requires `mediainfo`
# Find audio files (by default mp3 & m4a extensions) and check if they have AppleStoreAccount data

readarray -d '' audiof < <(find "$PWD" -name "*.mp3" -print0 -o -name "*.m4a" -print0)

echo "[+] found ${#audiof[@]} audio files"
for f in "${audiof[@]}"; do
  mediainfo --Inform="General;%AppleStoreAccount% %FileNameExtension%" "$f" | grep "@" && echo "$f"
done

echo "[=] Finished."
